import "./globals.css";

import SessionProvider from "@/providers/session-provider";

import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import React from "react";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <SessionProvider>{props.children}</SessionProvider>
      </body>
    </html>
  );
}
