import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";
import SessionProvider from "@/providers/session-provider";
import { cn } from "@/lib/utils";
import ModalProvider from "@/providers/modal-provider";

import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import React from "react";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Team Chat Application",
  description: "Generated by create next app",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(openSans.className, "bg-white dark:bg-[#313338]")}>
        <ThemeProvider
          storageKey="discord-theme"
          enableSystem={false}
          attribute="class"
          defaultTheme="light"
        >
          <SessionProvider>
            <ModalProvider />
            {props.children}
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
